import type { ParsedNote } from './vocab-import';

// Curated Lunfardo / casual Rioplatense starter deck. Shipped in-repo (not generated)
// so it's deterministic, free, and instantly available at setup.

export const LUNFARDO_DECK: ParsedNote[] = [
  { es: 'el laburo', en: 'work / job (casual)', example: 'Salgo del laburo a las siete.', exampleEn: 'I get off work at seven.', tags: ['lunfardo', 'noun'] },
  { es: 'laburar', en: 'to work (casual)', example: 'Mañana laburo hasta tarde.', exampleEn: 'Tomorrow I work late.', tags: ['lunfardo', 'verb'] },
  { es: 'el quilombo', en: 'a mess / chaos', example: 'El subte era un quilombo esta mañana.', exampleEn: 'The subway was chaos this morning.', tags: ['lunfardo', 'noun'] },
  { es: 'che', en: 'hey / dude (attention-getter)', example: 'Che, ¿me pasás la sal?', exampleEn: 'Hey, can you pass me the salt?', tags: ['lunfardo', 'interjection'] },
  { es: 'el boludo', en: 'dude / idiot (very informal, among friends)', example: '¿Todo bien, boludo?', exampleEn: 'All good, dude?', tags: ['lunfardo', 'noun'] },
  { es: 'la guita', en: 'money (slang)', example: 'No tengo guita hasta fin de mes.', exampleEn: 'I have no money until the end of the month.', tags: ['lunfardo', 'noun'] },
  { es: 'la plata', en: 'money (casual)', example: 'No me alcanza la plata este mes.', exampleEn: 'I don’t have enough money this month.', tags: ['lunfardo', 'noun'] },
  { es: 'el bondi', en: 'the bus (slang)', example: 'Me tomé el bondi hasta Caballito.', exampleEn: 'I took the bus to Caballito.', tags: ['lunfardo', 'transport'] },
  { es: 'el subte', en: 'the subway', example: 'El subte está lleno a las seis.', exampleEn: 'The subway is packed at six.', tags: ['transport', 'noun'] },
  { es: 'la mina', en: 'woman / girl (slang)', example: 'La mina del quiosco es re copada.', exampleEn: 'The woman at the kiosk is really cool.', tags: ['lunfardo', 'noun'] },
  { es: 'el pibe', en: 'kid / young guy', example: 'El pibe juega muy bien al fútbol.', exampleEn: 'The kid plays soccer really well.', tags: ['lunfardo', 'noun'] },
  { es: 'la fiaca', en: 'laziness / feeling lazy', example: 'Hoy tengo una fiaca terrible.', exampleEn: 'I’m feeling terribly lazy today.', tags: ['lunfardo', 'noun'] },
  { es: 'trucho', en: 'fake / low quality', example: 'Ese reloj es re trucho.', exampleEn: 'That watch is super fake.', tags: ['lunfardo', 'adjective'] },
  { es: 'posta', en: 'for real / the truth', example: 'Posta, la pizza de acá es la mejor.', exampleEn: 'For real, the pizza here is the best.', tags: ['lunfardo', 'adverb'] },
  { es: 'copado', en: 'cool / great', example: 'Tu amigo es re copado.', exampleEn: 'Your friend is really cool.', tags: ['lunfardo', 'adjective'] },
  { es: 'chamuyar', en: 'to sweet-talk / to BS', example: 'Me estaba chamuyando para llegar tarde.', exampleEn: 'He was sweet-talking me to excuse being late.', tags: ['lunfardo', 'verb'] },
  { es: 'morfar', en: 'to eat (slang)', example: '¿Vamos a morfar algo?', exampleEn: 'Shall we go eat something?', tags: ['lunfardo', 'verb'] },
  { es: 'la birra', en: 'beer (slang)', example: 'Nos tomamos una birra después del laburo.', exampleEn: 'We had a beer after work.', tags: ['lunfardo', 'noun'] },
  { es: 'el finde', en: 'the weekend (casual)', example: '¿Qué hacés el finde?', exampleEn: 'What are you doing on the weekend?', tags: ['lunfardo', 'noun'] },
  { es: 'dale', en: 'okay / go ahead / come on', example: 'Dale, nos vemos a las nueve.', exampleEn: 'Okay, see you at nine.', tags: ['lunfardo', 'interjection'] },
  { es: 'viste', en: 'you know / right?', example: 'Está lejos, viste, así que salí temprano.', exampleEn: 'It’s far, you know, so leave early.', tags: ['lunfardo', 'filler'] },
  { es: 're', en: 'very / super (intensifier)', example: 'Estoy re cansado hoy.', exampleEn: 'I’m super tired today.', tags: ['lunfardo', 'adverb'] },
  { es: 'capaz', en: 'maybe / perhaps', example: 'Capaz vamos al cine más tarde.', exampleEn: 'Maybe we’ll go to the movies later.', tags: ['lunfardo', 'adverb'] },
  { es: 'el kiosco', en: 'the corner store / kiosk', example: 'Compré caramelos en el kiosco.', exampleEn: 'I bought candy at the kiosk.', tags: ['noun', 'BA daily life'] },
  { es: 'la vereda', en: 'the sidewalk', example: 'Ojo, la vereda está rota ahí.', exampleEn: 'Careful, the sidewalk is broken there.', tags: ['noun', 'BA daily life'] },
  { es: 'el colectivo', en: 'the city bus', example: 'Me tomé el colectivo hasta Palermo.', exampleEn: 'I took the bus to Palermo.', tags: ['noun', 'transport'] },
  { es: 'la heladera', en: 'the fridge', example: 'Quedaron milanesas en la heladera.', exampleEn: 'There are milanesas left in the fridge.', tags: ['noun', 'apartment'] },
  { es: 'el departamento', en: 'the apartment', example: 'Alquilo un departamento en Almagro.', exampleEn: 'I rent an apartment in Almagro.', tags: ['noun', 'apartment'] },
  { es: 'la pileta', en: 'the pool / the sink', example: 'En verano vamos a la pileta del club.', exampleEn: 'In summer we go to the club pool.', tags: ['noun', 'BA daily life'] },
  { es: 'el asado', en: 'the barbecue', example: 'El domingo hacemos un asado en casa.', exampleEn: 'On Sunday we’re having a barbecue at home.', tags: ['noun', 'food'] },
  { es: 'la milanesa', en: 'breaded cutlet', example: 'Pedime una milanesa con puré.', exampleEn: 'Order me a milanesa with mashed potatoes.', tags: ['noun', 'food'] },
  { es: 'el mate', en: 'mate (the drink)', example: '¿Cebás unos mates?', exampleEn: 'Will you pour some mates?', tags: ['noun', 'food'] },
  { es: 'la factura', en: 'pastry (also: invoice)', example: 'Traje facturas para el desayuno.', exampleEn: 'I brought pastries for breakfast.', tags: ['noun', 'food'] },
  { es: 'el chabón', en: 'guy / dude (slang)', example: 'El chabón del kiosco me fió.', exampleEn: 'The guy at the kiosk gave me credit.', tags: ['lunfardo', 'noun'] },
  { es: 'zafar', en: 'to get by / to scrape through', example: 'Zafé del examen porque estudié anoche.', exampleEn: 'I scraped through the exam because I studied last night.', tags: ['lunfardo', 'verb'] },
  { es: 'el bardo', en: 'trouble / a scene', example: 'No hagas bardo en la fiesta.', exampleEn: 'Don’t make a scene at the party.', tags: ['lunfardo', 'noun'] },
  { es: 'engancharse', en: 'to get hooked / into something', example: 'Me enganché con esa serie.', exampleEn: 'I got hooked on that show.', tags: ['lunfardo', 'verb'] },
  { es: 'la joda', en: 'party / joke (slang)', example: 'Lo dije en joda, no te enojes.', exampleEn: 'I said it as a joke, don’t get mad.', tags: ['lunfardo', 'noun'] },
  { es: 'quedamos así', en: 'we’ll leave it like that', example: 'Dale, quedamos así entonces.', exampleEn: 'Okay, we’ll leave it like that then.', tags: ['lunfardo', 'phrase'] },
  { es: 'ni en pedo', en: 'no way (very informal)', example: 'Ni en pedo salgo con esta lluvia.', exampleEn: 'No way I’m going out in this rain.', tags: ['lunfardo', 'phrase'] },
];
