import type { Question } from './types';

export const QUESTION_BANK: Question[] = [

  // ─── A1 (difficulty 1–2) ─────────────────────────────────────────────────

  {
    prompt_id: 'LAR_A1_001',
    prompt_type: 'listen_and_respond',
    difficulty_score: 2.0,
    difficulty_bucket: 'A1',
    cefr_band: 'A1',
    skill_targets: ['greetings', 'basic_listening', 'basic_response'],
    audio_text: 'Hola, ¿cómo estás?',
    instruction_text: 'Listen and respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Bien.', 'Bien, gracias.', 'Muy bien.', 'Estoy bien.'],
    prompt_specific_grading_notes: ['Any natural greeting response counts. Do not require a specific phrase.'],
    dimension_weighting: { comprehension: 0.2, task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05, response_speed: 0.05 },
  },
  {
    prompt_id: 'LAR_A1_002',
    prompt_type: 'listen_and_respond',
    difficulty_score: 2.0,
    difficulty_bucket: 'A1',
    cefr_band: 'A1',
    skill_targets: ['invitation', 'basic_listening', 'basic_response'],
    audio_text: '¿Querés tomar un café?',
    instruction_text: 'Listen and respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Sí.', 'Sí, quiero.', 'Sí, dale.', 'No, gracias.'],
    prompt_specific_grading_notes: ['Accept any yes/no response. "Dale" counts as a natural Argentine acceptance.'],
    dimension_weighting: { comprehension: 0.2, task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05, response_speed: 0.05 },
  },
  {
    prompt_id: 'LAR_A1_003',
    prompt_type: 'listen_and_respond',
    difficulty_score: 2.6,
    difficulty_bucket: 'A1_PLUS',
    cefr_band: 'A1',
    skill_targets: ['personal_info', 'ser', 'basic_response'],
    audio_text: '¿De dónde sos?',
    instruction_text: 'Listen and respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Soy de Estados Unidos.', 'Soy de Nueva York.', 'Soy americano.'],
    prompt_specific_grading_notes: ['Accept any plausible country or city answer.'],
    dimension_weighting: { comprehension: 0.2, task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05, response_speed: 0.05 },
  },
  {
    prompt_id: 'SAY_A1_001',
    prompt_type: 'say_it_in_spanish',
    difficulty_score: 2.0,
    difficulty_bucket: 'A1',
    cefr_band: 'A1',
    skill_targets: ['want', 'basic_sentence', 'food_drink'],
    instruction_text: 'Say in Spanish: I want a coffee.',
    response_language_allowed: 'spanish',
    target_answer: 'Quiero un café.',
    acceptable_response_examples: ['Quiero un café.', 'Yo quiero un café.', 'Quisiera un café.'],
    prompt_specific_grading_notes: ['Meaning matters more than exact wording. "Quisiera" is more advanced but acceptable.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.25, vocabulary: 0.2, fluency: 0.1, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'SAY_A1_002',
    prompt_type: 'say_it_in_spanish',
    difficulty_score: 2.0,
    difficulty_bucket: 'A1',
    cefr_band: 'A1',
    skill_targets: ['negation', 'survival_phrase'],
    instruction_text: 'Say in Spanish: I don\'t understand.',
    response_language_allowed: 'spanish',
    target_answer: 'No entiendo.',
    acceptable_response_examples: ['No entiendo.', 'No comprendo.'],
    prompt_specific_grading_notes: ['Either verb is acceptable.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.25, vocabulary: 0.2, fluency: 0.1, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'SAY_A1_003',
    prompt_type: 'say_it_in_spanish',
    difficulty_score: 2.6,
    difficulty_bucket: 'A1_PLUS',
    cefr_band: 'A1',
    skill_targets: ['ser', 'personal_info', 'country'],
    instruction_text: 'Say in Spanish: I\'m from the United States.',
    response_language_allowed: 'spanish',
    target_answer: 'Soy de Estados Unidos.',
    acceptable_response_examples: ['Soy de Estados Unidos.', 'Vengo de Estados Unidos.'],
    prompt_specific_grading_notes: ['Accept "Vengo de" as an alternative to "Soy de".'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.25, vocabulary: 0.2, fluency: 0.1, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'LFM_A1_001',
    prompt_type: 'listen_for_meaning',
    difficulty_score: 2.6,
    difficulty_bucket: 'A1_PLUS',
    cefr_band: 'A1',
    skill_targets: ['basic_listening', 'food_drink', 'politeness'],
    audio_text: 'Quiero agua, por favor.',
    instruction_text: 'What did you understand? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands a request for water.',
    acceptable_response_examples: ['They want water.', 'I want water please.', 'Quiere agua.'],
    prompt_specific_grading_notes: ['Full credit for understanding the request. No need for exact Spanish.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'LFM_A1_002',
    prompt_type: 'listen_for_meaning',
    difficulty_score: 2.6,
    difficulty_bucket: 'A1_PLUS',
    cefr_band: 'A1',
    skill_targets: ['basic_listening', 'feelings', 'want'],
    audio_text: 'Estoy cansado y quiero dormir.',
    instruction_text: 'What did you understand? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the speaker is tired and wants to sleep.',
    acceptable_response_examples: ['They are tired and want to sleep.', 'Está cansado y quiere dormir.'],
    prompt_specific_grading_notes: ['Full credit for capturing both: tired + wants to sleep.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'ROLE_A1_001',
    prompt_type: 'roleplay_response',
    difficulty_score: 2.6,
    difficulty_bucket: 'A1_PLUS',
    cefr_band: 'A1',
    skill_targets: ['greetings', 'social_response', 'politeness'],
    scenario: 'Meeting someone new',
    audio_text: 'Hola, me llamo Laura. ¿Y vos?',
    instruction_text: 'Introduce yourself naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Me llamo...', 'Soy...', 'Mi nombre es...'],
    prompt_specific_grading_notes: ['Any introduction is acceptable. Award credit for any attempt.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'GRAM_A1_001',
    prompt_type: 'grammar_in_context',
    difficulty_score: 2.6,
    difficulty_bucket: 'A1_PLUS',
    cefr_band: 'A1',
    skill_targets: ['present_tense', 'verb_tener', 'age'],
    instruction_text: 'Say in Spanish: I am 30 years old.',
    response_language_allowed: 'spanish',
    target_answer: 'Tengo treinta años.',
    acceptable_response_examples: ['Tengo treinta años.', 'Tengo 30 años.'],
    prompt_specific_grading_notes: ['Spanish uses "tener" for age. Credit if they use the correct structure.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },

  // ─── A2 (difficulty 3–4) ─────────────────────────────────────────────────

  {
    prompt_id: 'LAR_A2_001',
    prompt_type: 'listen_and_respond',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['vos_recognition', 'availability', 'time'],
    audio_text: '¿Tenés tiempo mañana o estás ocupado?',
    instruction_text: 'Listen and respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Sí, tengo tiempo.', 'No, estoy ocupado.', 'Depende, ¿a qué hora?', 'Mañana no puedo.'],
    prompt_specific_grading_notes: ['Accept any natural availability response. Reward spontaneous follow-up questions.'],
    dimension_weighting: { comprehension: 0.2, task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05, response_speed: 0.05 },
  },
  {
    prompt_id: 'LAR_A2_002',
    prompt_type: 'listen_and_respond',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['choice', 'food', 'basic_conversation'],
    audio_text: '¿Querés comer algo ahora o después?',
    instruction_text: 'Listen and respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Ahora.', 'Después.', 'Prefiero comer después.', 'Sí, comamos ahora.'],
    prompt_specific_grading_notes: ['Any clear choice is acceptable.'],
    dimension_weighting: { comprehension: 0.2, task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05, response_speed: 0.05 },
  },
  {
    prompt_id: 'SAY_A2_001',
    prompt_type: 'say_it_in_spanish',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['ser', 'vivir', 'contrast', 'personal_info'],
    instruction_text: 'Say in Spanish: I\'m from the United States, but now I live in Argentina.',
    response_language_allowed: 'spanish',
    target_answer: 'Soy de Estados Unidos, pero ahora vivo en Argentina.',
    acceptable_response_examples: ['Soy de Estados Unidos, pero ahora vivo en Argentina.', 'Soy de Estados Unidos, pero ahora estoy viviendo en Argentina.'],
    prompt_specific_grading_notes: ['Contrast with "pero" is the target grammar. Accept simpler versions if meaning is clear.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.25, vocabulary: 0.2, fluency: 0.1, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'SAY_A2_002',
    prompt_type: 'say_it_in_spanish',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['near_future', 'plans', 'friend'],
    instruction_text: 'Say in Spanish: Tomorrow I\'m going to eat with a friend.',
    response_language_allowed: 'spanish',
    target_answer: 'Mañana voy a comer con un amigo.',
    acceptable_response_examples: ['Mañana voy a comer con un amigo.', 'Mañana voy a almorzar con un amigo.'],
    prompt_specific_grading_notes: ['"Voy a + infinitive" is the target structure for near future.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.25, vocabulary: 0.2, fluency: 0.1, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'SAY_A2_003',
    prompt_type: 'say_it_in_spanish',
    difficulty_score: 3.8,
    difficulty_bucket: 'A2',
    cefr_band: 'A2',
    skill_targets: ['request', 'vos', 'help'],
    instruction_text: 'Say in Spanish: Can you help me?',
    response_language_allowed: 'spanish',
    target_answer: '¿Podés ayudarme?',
    acceptable_response_examples: ['¿Podés ayudarme?', '¿Me podés ayudar?', '¿Puedes ayudarme?'],
    prompt_specific_grading_notes: ['Vos form "podés" preferred. Accept "puedes" without penalizing heavily.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.25, vocabulary: 0.2, fluency: 0.1, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'LFM_A2_001',
    prompt_type: 'listen_for_meaning',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['listening', 'time', 'contrast'],
    audio_text: 'El restaurante está cerrado hoy, pero abre mañana a las ocho.',
    instruction_text: 'What did you understand? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the restaurant is closed today but opens tomorrow at 8.',
    acceptable_response_examples: ['The restaurant is closed today and opens tomorrow at eight.', 'Está cerrado hoy y abre mañana a las ocho.'],
    prompt_specific_grading_notes: ['Full credit if they understand: closed today + opens tomorrow + time. Partial if only gist.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'LFM_A2_002',
    prompt_type: 'listen_for_meaning',
    difficulty_score: 3.8,
    difficulty_bucket: 'A2',
    cefr_band: 'A2',
    skill_targets: ['listening', 'reason', 'time'],
    audio_text: 'No puedo salir esta noche porque tengo que trabajar temprano mañana.',
    instruction_text: 'What did you understand? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the person cannot go out tonight because of early work tomorrow.',
    acceptable_response_examples: ["They can't go out tonight because they work early tomorrow.", 'No puede salir esta noche porque trabaja temprano mañana.'],
    prompt_specific_grading_notes: ['Full credit requires understanding: can\'t go out + reason (work early).'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'ROLE_A2_001',
    prompt_type: 'roleplay_response',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['requests', 'service_interaction', 'food_drink'],
    scenario: 'At a café',
    audio_text: 'Hola, ¿qué te traigo?',
    instruction_text: 'You\'re at a café. Respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Un café, por favor.', 'Quiero un café.', '¿Me traés un café?', 'Un café con leche y una medialuna, por favor.'],
    prompt_specific_grading_notes: ['Grade whether the response fits a café situation. Many valid answers.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'ROLE_A2_002',
    prompt_type: 'roleplay_response',
    difficulty_score: 3.8,
    difficulty_bucket: 'A2',
    cefr_band: 'A2',
    skill_targets: ['directions', 'location', 'asking_for_help'],
    scenario: 'On the street',
    audio_text: 'Perdón, ¿sabés cómo llegar a la estación de subte?',
    instruction_text: 'Someone is asking for directions. You don\'t know the way — respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['No sé.', 'Lo siento, no soy de acá.', 'No conozco bien la zona.', 'No, no sé, lo siento.'],
    prompt_specific_grading_notes: ['This is designed to elicit "I don\'t know" naturally. Credit if response fits the situation.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'OPEN_A2_001',
    prompt_type: 'open_speaking',
    difficulty_score: 3.2,
    difficulty_bucket: 'A2_MINUS',
    cefr_band: 'A2',
    skill_targets: ['personal_info', 'present_tense', 'daily_life'],
    instruction_text: 'Answer in Spanish: What do you usually do on weekends?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User describes weekend activities in basic sentences.',
    acceptable_response_examples: ['Los fines de semana salgo con amigos.', 'Normalmente descanso y veo películas.', 'Los sábados voy al gimnasio.'],
    prompt_specific_grading_notes: ['Accept basic sentences. Grade on communicative completeness, not variety.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'GRAM_A2_001',
    prompt_type: 'grammar_in_context',
    difficulty_score: 3.8,
    difficulty_bucket: 'A2',
    cefr_band: 'A2',
    skill_targets: ['gustar', 'opinion', 'food'],
    instruction_text: 'Say in Spanish: I really like Argentine food.',
    response_language_allowed: 'spanish',
    target_answer: 'Me gusta mucho la comida argentina.',
    acceptable_response_examples: ['Me gusta mucho la comida argentina.', 'La comida argentina me gusta mucho.', 'Me encanta la comida argentina.'],
    prompt_specific_grading_notes: ['Target is "gustar" structure. "Me encanta" is also correct and more enthusiastic.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },
  {
    prompt_id: 'PROB_A2_001',
    prompt_type: 'practical_problem',
    difficulty_score: 3.8,
    difficulty_bucket: 'A2',
    cefr_band: 'A2',
    skill_targets: ['asking_for_help', 'location', 'basic_request'],
    instruction_text: 'You\'re lost. Ask someone in Spanish: Excuse me, where is the nearest pharmacy?',
    response_language_allowed: 'spanish',
    target_answer: 'Perdón, ¿dónde está la farmacia más cercana?',
    acceptable_response_examples: ['Perdón, ¿dónde está la farmacia más cercana?', 'Disculpá, ¿hay una farmacia cerca?', '¿Dónde puedo encontrar una farmacia?'],
    prompt_specific_grading_notes: ['Accept polite variations. Grade on whether the request is clear and appropriate.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },

  // ─── B1 (difficulty 5–6) ─────────────────────────────────────────────────

  {
    prompt_id: 'OPEN_B1_001',
    prompt_type: 'open_speaking',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['past_tense', 'open_speaking', 'fluency'],
    instruction_text: 'Tell me in Spanish: What did you do yesterday?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User answers with at least one sentence describing yesterday.',
    acceptable_response_examples: ['Ayer fui a un restaurante.', 'Ayer trabajé y después salí a cenar.', 'Ayer fui a un restaurante con un amigo y después caminé un poco.'],
    prompt_specific_grading_notes: ['Key skill: past tense. Credit any coherent past-tense narration.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'OPEN_B1_002',
    prompt_type: 'open_speaking',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['opinion', 'reasoning', 'fluency'],
    instruction_text: 'Answer in Spanish: Do you prefer living in a big city or a small city? Why?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User states a preference and gives at least one reason.',
    acceptable_response_examples: ['Prefiero una ciudad grande porque hay más cosas para hacer.', 'Prefiero una ciudad chica porque es más tranquila.', 'Depende, pero ahora prefiero una ciudad grande porque me gusta conocer gente.'],
    prompt_specific_grading_notes: ['Grade on preference stated + reason given. Fluency is secondary here.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'OPEN_B1_003',
    prompt_type: 'open_speaking',
    difficulty_score: 5.8,
    difficulty_bucket: 'B1',
    cefr_band: 'B1',
    skill_targets: ['future_plans', 'reasoning', 'extended_speaking'],
    instruction_text: 'Answer in Spanish: What are your plans for the next few months?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User describes at least 2 future plans with reasons or details.',
    acceptable_response_examples: ['En los próximos meses voy a estudiar más español y también quiero viajar.', 'Planeo quedarme en Buenos Aires y buscar trabajo.'],
    prompt_specific_grading_notes: ['Credit for future tense usage and coherent plan description.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'GRAM_B1_001',
    prompt_type: 'grammar_in_context',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['preterite', 'imperfect', 'because', 'sequence'],
    instruction_text: 'Say in Spanish: Yesterday I went to dinner, but I came home early because I was tired.',
    response_language_allowed: 'spanish',
    target_answer: 'Ayer fui a cenar, pero volví temprano porque estaba cansado.',
    acceptable_response_examples: ['Ayer fui a cenar, pero volví temprano porque estaba cansado.', 'Ayer salí a cenar, pero regresé temprano porque estaba cansado.'],
    prompt_specific_grading_notes: ['This tests preterite/imperfect contrast. Do not require perfect tense for partial credit.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },
  {
    prompt_id: 'GRAM_B1_002',
    prompt_type: 'grammar_in_context',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['near_future', 'sequence', 'plans'],
    instruction_text: 'Say in Spanish: Tomorrow I\'m going to meet a friend, and after that we\'re going to eat something.',
    response_language_allowed: 'spanish',
    target_answer: 'Mañana me voy a juntar con un amigo y después vamos a comer algo.',
    acceptable_response_examples: ['Mañana me voy a juntar con un amigo y después vamos a comer algo.', 'Mañana voy a encontrarme con un amigo y después vamos a comer algo.'],
    prompt_specific_grading_notes: ['"Juntarse" is the Argentine term for meeting up. Accept "encontrarse" or "reunirse".'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },
  {
    prompt_id: 'GRAM_B1_003',
    prompt_type: 'grammar_in_context',
    difficulty_score: 5.8,
    difficulty_bucket: 'B1',
    cefr_band: 'B1',
    skill_targets: ['subjunctive', 'request', 'need'],
    instruction_text: 'Say in Spanish: I need you to call me when you arrive.',
    response_language_allowed: 'spanish',
    target_answer: 'Necesito que me llames cuando llegues.',
    acceptable_response_examples: ['Necesito que me llames cuando llegues.', 'Necesito que me llamés cuando llegués.', 'Necesito que me avises cuando llegues.'],
    prompt_specific_grading_notes: ['Tests subjunctive in noun clause ("que + subjunctive"). Partial credit if meaning is clear but tense is wrong.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },
  {
    prompt_id: 'MDC_B1_001',
    prompt_type: 'mini_dialogue_comprehension',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['dialogue_comprehension', 'plans', 'inference'],
    audio_text: 'Persona A: Che, ¿querés ir a cenar después? Persona B: Hoy no puedo, tengo que terminar algo del laburo. ¿Mañana te va? Persona A: Sí, mañana perfecto.',
    instruction_text: 'What did they decide? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands they rescheduled dinner to tomorrow.',
    acceptable_response_examples: ["They're going to dinner tomorrow because one person can't tonight.", 'Uno no puede hoy por trabajo, entonces van mañana.'],
    prompt_specific_grading_notes: ['Full credit requires: today doesn\'t work + agreed on tomorrow.'],
    dimension_weighting: { comprehension: 0.45, task_completion: 0.35, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'MDC_B1_002',
    prompt_type: 'mini_dialogue_comprehension',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['dialogue_comprehension', 'waiting', 'sequence'],
    audio_text: 'Persona A: ¿Ya pediste la comida? Persona B: No, todavía no. Estoy esperando a Laura. Persona A: Bueno, cuando llegue pedimos todo junto.',
    instruction_text: 'What are they waiting for? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands they are waiting for Laura to order together.',
    acceptable_response_examples: ["They're waiting for Laura before ordering.", 'Esperan a Laura para pedir juntos.'],
    prompt_specific_grading_notes: ['Full credit: waiting for Laura + will order when she arrives.'],
    dimension_weighting: { comprehension: 0.45, task_completion: 0.35, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'MDC_B1_003',
    prompt_type: 'mini_dialogue_comprehension',
    difficulty_score: 5.8,
    difficulty_bucket: 'B1',
    cefr_band: 'B1',
    skill_targets: ['dialogue_comprehension', 'problem', 'inference'],
    audio_text: 'Persona A: ¿Cómo te fue en la entrevista? Persona B: Más o menos. Creo que me fue bien, pero no sé si les gusté. Persona A: ¿Por qué decís eso? Persona B: Porque al final me dijeron que iban a llamar, pero no pusieron fecha.',
    instruction_text: 'Why is Persona B unsure about the interview? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the person felt okay but is uncertain because no date was given for a callback.',
    acceptable_response_examples: ["They said they'd call but didn't give a date, so they're not sure.", 'Le dijeron que iban a llamar pero no dieron fecha.'],
    prompt_specific_grading_notes: ['Full credit: uncertain + specific reason (no date given).'],
    dimension_weighting: { comprehension: 0.45, task_completion: 0.35, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'PROB_B1_001',
    prompt_type: 'practical_problem',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['problem_explanation', 'request', 'housing'],
    instruction_text: 'You\'re staying in an apartment. Tell the owner in Spanish: The hot water isn\'t working, and I need someone to check it today.',
    response_language_allowed: 'spanish',
    target_answer: 'No funciona el agua caliente y necesito que alguien lo revise hoy.',
    acceptable_response_examples: ['No funciona el agua caliente y necesito que alguien lo revise hoy.', 'No anda el agua caliente. ¿Puede venir alguien hoy?', 'El agua caliente no funciona. Necesito ayuda hoy.'],
    prompt_specific_grading_notes: ['Accept "no anda" as natural Argentine. Both problem + today\'s urgency needed for full credit.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'PROB_B1_002',
    prompt_type: 'practical_problem',
    difficulty_score: 5.8,
    difficulty_bucket: 'B1',
    cefr_band: 'B1',
    skill_targets: ['negotiation', 'price', 'shopping'],
    instruction_text: 'You\'re buying something at a market and the price seems too high. Ask in Spanish if they can give you a better price.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User asks for a discount or better price politely.',
    acceptable_response_examples: ['¿No me podés hacer un poco más barato?', '¿Hay algún descuento?', '¿Me lo dejás en menos?', 'Es un poco caro para mí, ¿podemos arreglar el precio?'],
    prompt_specific_grading_notes: ['Any polite price negotiation counts. Reward Argentine-sounding phrasing.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'LFM_B1_001',
    prompt_type: 'listen_for_meaning',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['natural_listening', 'reason', 'time', 'request'],
    audio_text: 'Che, perdón, llego un poco tarde porque hay mucho tráfico. ¿Podés esperarme diez minutos?',
    instruction_text: 'What happened? You can answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the person is running late due to traffic and asks to wait 10 minutes.',
    acceptable_response_examples: ["They're running late because of traffic and want me to wait ten minutes.", 'Llega tarde por el tráfico y pide que espere diez minutos.'],
    prompt_specific_grading_notes: ['Full credit: late + reason (traffic) + request (wait 10 min).'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'ROLE_B1_001',
    prompt_type: 'roleplay_response',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['work_context', 'explaining', 'politeness'],
    scenario: 'In the office',
    audio_text: 'Necesito que me entregués el informe antes del viernes. ¿Podés?',
    instruction_text: 'Your manager asks you to deliver a report by Friday. Respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Sí, sin problema.', 'Sí, lo tengo listo para el jueves.', 'Creo que sí, pero necesito un poco más de información.'],
    prompt_specific_grading_notes: ['Any natural workplace confirmation or clarification counts.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'ROLE_B1_002',
    prompt_type: 'roleplay_response',
    difficulty_score: 5.8,
    difficulty_bucket: 'B1',
    cefr_band: 'B1',
    skill_targets: ['restaurant', 'complaint', 'polite_correction'],
    scenario: 'At a restaurant',
    audio_text: 'Acá está su pedido: una milanesa con papas fritas.',
    instruction_text: 'You ordered a salad, not milanesa. Politely correct the mistake in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Perdón, creo que hay un error. Yo pedí una ensalada.', 'Disculpá, no es lo que pedí. Yo había pedido una ensalada.', 'Creo que hay una confusión, pedí una ensalada.'],
    prompt_specific_grading_notes: ['Credit for polite correction. Do not require formal register.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'LAR_B1_001',
    prompt_type: 'listen_and_respond',
    difficulty_score: 5.2,
    difficulty_bucket: 'B1_MINUS',
    cefr_band: 'B1',
    skill_targets: ['natural_speed', 'opinion', 'fluency'],
    audio_text: 'Mirá, lo que te digo es importante. Tenés que tomar una decisión antes del lunes.',
    instruction_text: 'Listen and respond naturally in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Sí, lo entiendo.', 'De acuerdo, voy a pensarlo.', 'Está bien, lo voy a considerar.', 'Sí, te escucho. ¿Me podés dar más detalles?'],
    prompt_specific_grading_notes: ['Any natural response showing understanding of the urgency counts.'],
    dimension_weighting: { comprehension: 0.2, task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05, response_speed: 0.05 },
  },

  // ─── B2 (difficulty 7–8) ─────────────────────────────────────────────────

  {
    prompt_id: 'MON_B2_001',
    prompt_type: 'monologue_comprehension',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['summary', 'opinion', 'detail_comprehension'],
    audio_text: 'La verdad, me gusta vivir en una ciudad grande, pero a veces cansa. Tenés muchas opciones, siempre hay algo para hacer, pero también hay ruido, tráfico y mucha gente todo el tiempo. Creo que depende mucho de la etapa de tu vida.',
    instruction_text: 'What did the person talk about? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User captures pros, cons, and the nuance that it depends on life stage.',
    acceptable_response_examples: ['They talked about the pros and cons of living in a big city.', 'Le gusta la ciudad grande, pero cansa por el ruido y el tráfico.'],
    prompt_specific_grading_notes: ['Full credit: likes big city + tiring + depends on life stage. Partial: just pros or just cons.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, vocabulary: 0.1, fluency: 0.1 },
  },
  {
    prompt_id: 'MON_B2_002',
    prompt_type: 'monologue_comprehension',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['summary', 'abstract_listening', 'contrast'],
    audio_text: 'Antes pensaba que aprender un idioma era principalmente estudiar gramática, pero ahora creo que lo más importante es usarlo todos los días. Si no hablás, no lo incorporás de verdad, aunque entiendas las reglas.',
    instruction_text: 'What is the speaker\'s main point? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the shift from grammar-focused to usage-focused language learning.',
    acceptable_response_examples: ['They think using the language every day is more important than studying grammar.', 'Antes pensaba en la gramática, pero ahora cree que hay que hablarlo todos los días.'],
    prompt_specific_grading_notes: ['Full credit: grammar isn\'t enough + daily use is key.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, vocabulary: 0.1, fluency: 0.1 },
  },
  {
    prompt_id: 'MON_B2_003',
    prompt_type: 'monologue_comprehension',
    difficulty_score: 7.8,
    difficulty_bucket: 'B2',
    cefr_band: 'B2',
    skill_targets: ['detail_comprehension', 'opinion', 'nuance'],
    audio_text: 'Me parece que el problema con el trabajo remoto no es la productividad, sino la falta de límites. Cuando tu casa es tu oficina, es difícil desconectarte. Terminás respondiendo mensajes a las once de la noche porque el teléfono siempre está ahí.',
    instruction_text: 'What problem is the speaker describing? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User identifies the main issue as difficulty setting limits when working from home.',
    acceptable_response_examples: ['The problem with remote work is not being able to disconnect and set limits.', 'El problema es que no podés separar el trabajo de la vida personal.'],
    prompt_specific_grading_notes: ['Main point: not productivity — blurry limits/work-life balance.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, vocabulary: 0.1, fluency: 0.1 },
  },
  {
    prompt_id: 'OPEN_B2_001',
    prompt_type: 'open_speaking',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['comparison', 'extended_speaking', 'opinion', 'contrast'],
    instruction_text: 'Answer in Spanish for about 30 seconds: What is one thing that is easier in your home country than in Argentina, and one thing that is better in Argentina?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User compares both places with at least one example each side.',
    acceptable_response_examples: ['En Estados Unidos es más fácil hacer trámites online, pero en Argentina la vida social es mejor.', 'Creo que en mi país algunas cosas son más organizadas, pero en Argentina es más fácil conocer gente.'],
    prompt_specific_grading_notes: ['Full credit: two-sided comparison with at least one specific example.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'OPEN_B2_002',
    prompt_type: 'open_speaking',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['abstract_speaking', 'opinion', 'examples'],
    instruction_text: 'Answer in Spanish: What makes a city feel like a good place to live?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User explains several factors, possibly with examples.',
    acceptable_response_examples: ['Para mí, una ciudad es buena si tiene buena comida, gente interesante, transporte fácil y lugares para caminar.', 'Creo que depende de la seguridad, la vida social, el clima y las oportunidades.'],
    prompt_specific_grading_notes: ['Grade on range of ideas and ability to explain. More than one factor needed for full credit.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'OPEN_B2_003',
    prompt_type: 'open_speaking',
    difficulty_score: 7.8,
    difficulty_bucket: 'B2',
    cefr_band: 'B2',
    skill_targets: ['hypothetical', 'extended_speaking', 'conditional'],
    instruction_text: 'Answer in Spanish: If you could live anywhere in the world, where would you choose and why?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User uses conditional or hypothetical structures and gives a detailed reason.',
    acceptable_response_examples: ['Si pudiera vivir en cualquier lugar, elegiría Tokio porque me parece fascinante.', 'Elegiría una ciudad costera, probablemente en Europa, porque me encanta el mar y la cultura.'],
    prompt_specific_grading_notes: ['Target: conditional phrasing. Full credit for any structured hypothetical with clear reasoning.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'PROB_B2_001',
    prompt_type: 'practical_problem',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['problem_explanation', 'politeness', 'past_tense', 'request'],
    instruction_text: 'You booked an apartment, but when you arrived the internet didn\'t work and the owner didn\'t answer your messages. Explain the situation politely and ask for a solution today.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User describes the problem, mentions failed communication, and requests a solution.',
    acceptable_response_examples: ['Llegué al departamento y no funciona internet. Te escribí antes, pero no recibí respuesta. Necesito una solución hoy, por favor.', 'Cuando llegué, el wifi no andaba y traté de comunicarme, pero nadie me contestó. ¿Podemos resolverlo hoy?'],
    prompt_specific_grading_notes: ['Three elements for full credit: problem described + failed contact + request for today.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'PROB_B2_002',
    prompt_type: 'practical_problem',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['formal_register', 'explanation', 'work_context'],
    instruction_text: 'You missed an important meeting at work. Send a message in Spanish to your boss explaining what happened and offering a solution.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User explains absence, gives a reason, and proposes a follow-up.',
    acceptable_response_examples: ['Hola, te quería pedir disculpas por no haber podido llegar a la reunión. Tuve un imprevisto. ¿Podemos reprogramarla para mañana?', 'Perdón por no estar en la reunión. Tuve un problema de último momento. ¿Me podés contar cómo les fue y cómo puedo ayudar?'],
    prompt_specific_grading_notes: ['Full credit: apology + reason + proposed solution.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'PROB_B2_003',
    prompt_type: 'practical_problem',
    difficulty_score: 7.8,
    difficulty_bucket: 'B2',
    cefr_band: 'B2',
    skill_targets: ['negotiation', 'formal_register', 'extended_explanation'],
    instruction_text: 'You hired someone for a job and the result was not what you expected. Explain in Spanish what was wrong and what you expect them to fix.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User clearly describes what fell short and states expectations for correction.',
    acceptable_response_examples: ['El trabajo no quedó como acordamos. Hablamos de un diseño más simple, pero el resultado es muy recargado. Necesito que lo revises y lo simplificás.', 'La entrega no es lo que esperábamos. ¿Podés hacer los ajustes que te indiqué antes?'],
    prompt_specific_grading_notes: ['Full credit: what went wrong + what needs to change. Professional register is a plus.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },
  {
    prompt_id: 'MDC_B2_001',
    prompt_type: 'mini_dialogue_comprehension',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['inference', 'subtext', 'dialogue_comprehension'],
    audio_text: 'Persona A: ¿Entonces vas a hablar con él? Persona B: Sí, pero no sé cómo va a reaccionar. La última vez no fue muy bien. Persona A: Bueno, es mejor que no decirle nada.',
    instruction_text: 'What is the situation and what is Persona B worried about? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User infers B needs to have a difficult conversation and is worried because it went badly last time.',
    acceptable_response_examples: ['Persona B has to talk to someone but is worried because last time it went badly.', 'Tiene que hablar con alguien pero le preocupa la reacción porque la última vez fue mal.'],
    prompt_specific_grading_notes: ['Full credit: impending conversation + worry about reaction + reference to last time.'],
    dimension_weighting: { comprehension: 0.45, task_completion: 0.35, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'MDC_B2_002',
    prompt_type: 'mini_dialogue_comprehension',
    difficulty_score: 7.8,
    difficulty_bucket: 'B2',
    cefr_band: 'B2',
    skill_targets: ['inference', 'tone', 'social_pragmatics'],
    audio_text: 'Persona A: ¿Cómo vas con el proyecto? Persona B: Bien, bien. Va a salir. Persona A: ¿Seguro? Persona B: Sí, no te preocupes. Persona A: Es que el cliente preguntó hoy.',
    instruction_text: 'What is the tension in this conversation? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User detects that Person A is under pressure from a client and is not fully convinced by B\'s reassurance.',
    acceptable_response_examples: ["Person A is not convinced by B's reassurance because the client is asking.", 'Persona A no está del todo convencida de que va a salir bien, y encima el cliente está preguntando.'],
    prompt_specific_grading_notes: ['Subtle inference required. Credit for picking up on A\'s doubt and the client pressure.'],
    dimension_weighting: { comprehension: 0.45, task_completion: 0.35, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'LFM_B2_001',
    prompt_type: 'listen_for_meaning',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['clarification', 'negation', 'inference'],
    audio_text: 'No dije que no quería ir. Dije que no sabía si iba a llegar a tiempo.',
    instruction_text: 'What is the speaker clarifying? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the speaker is correcting a misunderstanding about their intent.',
    acceptable_response_examples: ["They're saying they do want to go, but they're not sure they'll be on time.", 'No dijo que no quería ir, sino que no sabía si llegaba a tiempo.'],
    prompt_specific_grading_notes: ['Must capture the distinction: NOT "doesn\'t want to go" but "not sure about timing".'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, fluency: 0.1, response_speed: 0.1 },
  },
  {
    prompt_id: 'GRAM_B2_001',
    prompt_type: 'grammar_in_context',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['past_perfect', 'sequence', 'explanation'],
    instruction_text: 'Say in Spanish: By the time I arrived, they had already left.',
    response_language_allowed: 'spanish',
    target_answer: 'Cuando llegué, ya se habían ido.',
    acceptable_response_examples: ['Cuando llegué, ya se habían ido.', 'Cuando llegué ya habían salido.', 'Para cuando llegué ya se habían ido.'],
    prompt_specific_grading_notes: ['Target: past perfect (había/habían + past participle). Partial credit if meaning is clear without perfect tense.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },
  {
    prompt_id: 'GRAM_B2_002',
    prompt_type: 'grammar_in_context',
    difficulty_score: 7.8,
    difficulty_bucket: 'B2',
    cefr_band: 'B2',
    skill_targets: ['conditional', 'hypothetical', 'complex_sentence'],
    instruction_text: 'Say in Spanish: If I had known about the problem earlier, I would have fixed it.',
    response_language_allowed: 'spanish',
    target_answer: 'Si lo hubiera sabido antes, lo habría arreglado.',
    acceptable_response_examples: ['Si lo hubiera sabido antes, lo habría arreglado.', 'Si hubiera sabido el problema antes, lo habría resuelto.'],
    prompt_specific_grading_notes: ['Tests past conditional (hubiera + habría). Partial credit for present conditional if structure shows the right intent.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.35, vocabulary: 0.15, fluency: 0.1, pronunciation_intelligibility: 0.05 },
  },
  {
    prompt_id: 'ROLE_B2_001',
    prompt_type: 'roleplay_response',
    difficulty_score: 7.2,
    difficulty_bucket: 'B2_MINUS',
    cefr_band: 'B2',
    skill_targets: ['social_pragmatics', 'politeness', 'naturalaness'],
    scenario: 'Dinner with friends',
    audio_text: 'Mirá, la verdad es que esta semana estoy con mil cosas. Me encantaría juntarme, pero si puede ser, prefiero dejarlo para la semana que viene.',
    instruction_text: 'A friend wants to reschedule. Respond naturally and warmly in Spanish.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Sí, obvio, no hay problema. Lo dejamos para la semana que viene.', 'Dale, tranqui. Cuando estés más libre arreglamos.', 'No te preocupes, entiendo. La semana que viene me viene bien también.'],
    prompt_specific_grading_notes: ['Reward natural, warm social register. Cold or abrupt replies should get partial credit.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },

  // ─── C1 (difficulty 9–10) ─────────────────────────────────────────────────

  {
    prompt_id: 'MON_C1_001',
    prompt_type: 'monologue_comprehension',
    difficulty_score: 9.2,
    difficulty_bucket: 'C1_MINUS',
    cefr_band: 'C1',
    skill_targets: ['nuance', 'abstract_listening', 'summary', 'social_pragmatics'],
    audio_text: 'Lo que más me cuesta de vivir afuera no es tanto el idioma, sino la sensación de tener que reinterpretar todo el tiempo las reglas sociales. Cosas que en tu país son automáticas, en otro lugar requieren energía mental: cómo saludar, cuándo insistir, cuándo callarte, cómo sonar amable sin parecer demasiado formal.',
    instruction_text: 'What is the speaker saying? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User captures the nuance: not language itself but the cognitive load of re-learning social rules.',
    acceptable_response_examples: ["They're saying living abroad is hard because social rules need constant re-interpretation, not just the language.", 'Dice que lo difícil no es el idioma sino entender las reglas sociales que en tu país son automáticas.'],
    prompt_specific_grading_notes: ['Full credit: main challenge = social rules (not language) + specific examples of social rules.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, vocabulary: 0.1, fluency: 0.1 },
  },
  {
    prompt_id: 'MON_C1_002',
    prompt_type: 'monologue_comprehension',
    difficulty_score: 9.2,
    difficulty_bucket: 'C1_MINUS',
    cefr_band: 'C1',
    skill_targets: ['abstract_listening', 'argument', 'nuance'],
    audio_text: 'Hay una diferencia entre saber hablar un idioma y sentirte cómodo en él. Yo sé francés, lo puedo usar, pero cuando estoy cansado o estresado, me cuesta. El idioma real es el que te sale en esos momentos, no cuando estás descansado y preparado.',
    instruction_text: 'What distinction is the speaker making? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the difference between knowing a language and being truly comfortable in it, especially under stress.',
    acceptable_response_examples: ['The speaker distinguishes knowing a language from being truly fluent, especially when tired or stressed.', 'Hace una diferencia entre saber el idioma y sentirte cómodo: el idioma real sale cuando estás cansado.'],
    prompt_specific_grading_notes: ['Key distinction: performance under normal conditions vs. under stress. Both sides needed for full credit.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, vocabulary: 0.1, fluency: 0.1 },
  },
  {
    prompt_id: 'MON_C1_003',
    prompt_type: 'monologue_comprehension',
    difficulty_score: 9.7,
    difficulty_bucket: 'C1',
    cefr_band: 'C1',
    skill_targets: ['implied_meaning', 'abstract_listening', 'critical_thinking'],
    audio_text: 'La nostalgia es curiosa. Te hace recordar cosas que probablemente no fueron tan buenas como las recordás. Pero eso no importa, porque la función de la nostalgia no es ser exacta, sino darte un lugar adonde volver mentalmente cuando el presente se pone difícil.',
    instruction_text: 'What is the speaker saying about nostalgia? Answer in English or Spanish.',
    response_language_allowed: 'english_or_spanish',
    expected_answer_behavior: 'User understands the argument: nostalgia isn\'t accurate but serves a psychological function.',
    acceptable_response_examples: ["Nostalgia doesn't need to be accurate — it gives you a mental refuge when things are hard.", 'La nostalgia no es exacta, pero sirve para tener un lugar mental adonde ir cuando el presente está difícil.'],
    prompt_specific_grading_notes: ['Full credit: nostalgia = not accurate + psychological function of escape.'],
    dimension_weighting: { comprehension: 0.5, task_completion: 0.3, vocabulary: 0.1, fluency: 0.1 },
  },
  {
    prompt_id: 'OPEN_C1_001',
    prompt_type: 'open_speaking',
    difficulty_score: 9.2,
    difficulty_bucket: 'C1_MINUS',
    cefr_band: 'C1',
    skill_targets: ['abstract_speaking', 'argument', 'nuance', 'extended_fluency'],
    instruction_text: 'Answer in Spanish for about 45 seconds: Do you think learning a language is more about memorizing correct forms or becoming comfortable with uncertainty? Explain your view.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User sustains an abstract explanation, contrasts two ideas, and gives a nuanced opinion.',
    acceptable_response_examples: ['Creo que al principio necesitás memorizar ciertas formas básicas, pero después lo más importante es tolerar la incertidumbre y seguir hablando aunque no estés seguro.', 'Para mí, las dos cosas importan, pero la comodidad con la incertidumbre es lo que te permite usar el idioma en la vida real.'],
    prompt_specific_grading_notes: ['Grade on depth of argument and sustained fluency. Simple binary answers get partial credit.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'OPEN_C1_002',
    prompt_type: 'open_speaking',
    difficulty_score: 9.7,
    difficulty_bucket: 'C1',
    cefr_band: 'C1',
    skill_targets: ['abstract_speaking', 'critical_analysis', 'extended_fluency'],
    instruction_text: 'Answer in Spanish for about 45 seconds: What do you think is lost and what is gained when you adopt a new language and culture?',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User presents a multi-sided argument with personal or general examples.',
    acceptable_response_examples: ['Creo que ganás perspectiva y herramientas nuevas para ver el mundo, pero a veces perdés la comodidad de expresarte con matices en tu idioma nativo.'],
    prompt_specific_grading_notes: ['Full credit for both sides with specific examples. One-sided response gets partial credit.'],
    dimension_weighting: { fluency: 0.25, grammar: 0.2, vocabulary: 0.2, task_completion: 0.2, pronunciation_intelligibility: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'ROLE_C1_001',
    prompt_type: 'roleplay_response',
    difficulty_score: 9.2,
    difficulty_bucket: 'C1_MINUS',
    cefr_band: 'C1',
    skill_targets: ['pragmatics', 'politeness', 'social_response', 'naturalness'],
    scenario: 'Social plans',
    audio_text: 'Mirá, la verdad es que esta semana estoy con mil cosas. Me encantaría juntarme, pero si puede ser, prefiero dejarlo para la semana que viene.',
    instruction_text: 'Respond naturally and politely in Spanish. Show you understand the situation.',
    response_language_allowed: 'spanish',
    acceptable_response_examples: ['Sí, obvio, no hay problema. Lo dejamos para la semana que viene.', 'Dale, tranqui. Cuando estés más libre arreglamos.', 'No te preocupes, entiendo. La semana que viene me viene bien también.'],
    prompt_specific_grading_notes: ['Grade on natural tone and social register. C1 level expects idiomatic phrasing and warmth.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'ROLE_C1_002',
    prompt_type: 'roleplay_response',
    difficulty_score: 9.7,
    difficulty_bucket: 'C1',
    cefr_band: 'C1',
    skill_targets: ['professional_register', 'tact', 'nuance', 'complex_communication'],
    scenario: 'Giving critical feedback',
    audio_text: 'Bueno, ¿qué te pareció mi presentación? Sé honesto.',
    instruction_text: 'Your colleague did an okay job but it needs clear improvement. Give honest but tactful feedback in Spanish.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User gives a nuanced response that acknowledges strengths and diplomatically addresses weaknesses.',
    acceptable_response_examples: ['Me pareció que la estructura estaba bien, pero creo que faltó profundizar en algunos puntos clave.', 'La presentación tuvo cosas buenas, como la claridad visual, pero sentí que el argumento central podría ser más convincente.'],
    prompt_specific_grading_notes: ['Full credit: positive element + specific constructive criticism. Brutal honesty without tact = partial credit.'],
    dimension_weighting: { task_completion: 0.3, grammar: 0.15, vocabulary: 0.15, fluency: 0.15, pronunciation_intelligibility: 0.1, response_speed: 0.1, target_style_alignment: 0.05 },
  },
  {
    prompt_id: 'PROB_C1_001',
    prompt_type: 'practical_problem',
    difficulty_score: 9.2,
    difficulty_bucket: 'C1_MINUS',
    cefr_band: 'C1',
    skill_targets: ['formal_register', 'advocacy', 'complex_explanation'],
    instruction_text: 'You received an incorrect bill for a service you didn\'t use. Explain the situation in Spanish to customer service and ask them to reverse the charge.',
    response_language_allowed: 'spanish',
    expected_answer_behavior: 'User explains the error clearly, references what they did/didn\'t use, and requests a specific action.',
    acceptable_response_examples: ['Hola, les escribo porque recibí un cobro por un servicio que no utilicé. Les pido que revisen mi cuenta y que me acrediten el importe lo antes posible.', 'Buen día. Quisiera hacer una reclamación porque me facturaron un servicio al que no accedí. Agradecería que reviertan el cargo en mi cuenta.'],
    prompt_specific_grading_notes: ['Full credit: error described precisely + specific resolution requested + appropriate formal register.'],
    dimension_weighting: { task_completion: 0.35, grammar: 0.2, vocabulary: 0.2, fluency: 0.15, pronunciation_intelligibility: 0.1 },
  },
];
